.TH "Graph" 3 "Tue Dec 13 2022" "Gestionnaire de parkings intelligents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGraph\fP ()"
.br
.RI "constructeur par défaut, utiliser uniquement dans le test régression\&. "
.ti -1c
.RI "\fB~Graph\fP ()"
.br
.RI "destructeur de graph\&. "
.ti -1c
.RI "\fBGraph\fP (vector< pair< double, double >> data1_, vector< pair< double, double >> data2_, vector< pair< double, double >> data3_, string graphName_, int xMin_, int yMin_, int xMax_, int yMax_)"
.br
.RI "constructeur de graphiques prenant trois source de données différentes, pour comparer les courbes de 3 parkings par exemples\&. "
.ti -1c
.RI "\fBGraph\fP (vector< pair< double, double >> data1_, string graphName_, int xMin_, int yMin_, int xMax_, int yMax_)"
.br
.RI "constructeur de grahique avec courbe unique\&. "
.ti -1c
.RI "int \fBcreateGraph\fP ()"
.br
.RI "fonction de création de graphique\&. "
.ti -1c
.RI "void \fBtest_regression\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int Graph::createGraph ()"

.PP
fonction de création de graphique\&. 
.PP
\fBReturns\fP
.RS 4
retourne 0 si pas d'erreur, -1 sinon\&. 
.br
 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gestionnaire de parkings intelligents from the source code\&.
