.TH "Menu" 3 "Tue Dec 13 2022" "Gestionnaire de parkings intelligents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitMenu\fP ()"
.br
.ti -1c
.RI "void \fBinitFont\fP ()"
.br
.ti -1c
.RI "void \fBinitTexture\fP ()"
.br
.ti -1c
.RI "void \fBdestructMenu\fP ()"
.br
.ti -1c
.RI "void \fBafficherMenu\fP ()"
.br
.ti -1c
.RI "void \fBlaunchSim\fP ()"
.br
.ti -1c
.RI "void \fBmenuLoop\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gestionnaire de parkings intelligents from the source code\&.
