.TH "Message" 3 "Tue Dec 13 2022" "Gestionnaire de parkings intelligents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP ()"
.br
.RI "constructeur par défaut du message "
.ti -1c
.RI "\fBMessage\fP (string aSender, string aRecipient)"
.br
.RI "1er constructeur à paramètres du message "
.ti -1c
.RI "\fBMessage\fP (unsigned int aMessageNumber, float aPrice, string aSubject, string aSender, string aRecipient)"
.br
.RI "2e constructeur à paramètres du message "
.ti -1c
.RI "\fBMessage\fP (const \fBMessage\fP &aMessage)"
.br
.RI "Constructeur par copie\&. "
.ti -1c
.RI "\fB~Message\fP ()"
.br
.RI "destructeur du message "
.ti -1c
.RI "const unsigned int & \fBgetMessageNumber\fP () const"
.br
.RI "procédure de récupération du numéro du message "
.ti -1c
.RI "const string & \fBgetSubject\fP () const"
.br
.RI "procédure de récupération de l'objet du message "
.ti -1c
.RI "clock_t \fBgetDate\fP () const"
.br
.RI "procédure de récupération de la date du message "
.ti -1c
.RI "float \fBgetPrice\fP () const"
.br
.RI "procédure de récupération du tarif indiqué dans le message "
.ti -1c
.RI "const string & \fBgetSender\fP () const"
.br
.RI "procédure de récupération de l'expéditeur du message "
.ti -1c
.RI "const string & \fBgetRecipient\fP () const"
.br
.RI "procédure de récupération du destinataire du message "
.ti -1c
.RI "void \fBtest_regresion\fP ()"
.br
.RI "test de régression de la classe \fBMessage\fP\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Message::Message (string aSender, string aRecipient)"

.PP
1er constructeur à paramètres du message Utilisé pour créer le 1er message d'une conversation 
.PP
\fBParameters\fP
.RS 4
\fIaSender\fP expéditeur du message 
.br
\fIaRecipient\fP destinataire du message 
.RE
.PP

.SS "Message::Message (unsigned int aMessageNumber, float aPrice, string aSubject, string aSender, string aRecipient)"

.PP
2e constructeur à paramètres du message Utilisé pour créer tout les messages qui ne sont pas
.PP
le 1er message d'une conversation 
.PP
\fBParameters\fP
.RS 4
\fIaMessageNumber\fP numéro du message 
.br
\fIaPrice\fP prix proposé 
.br
\fIaSubject\fP type du message 
.br
\fIaSender\fP expéditeur du message 
.br
\fIaRecipient\fP destinataire du message 
.RE
.PP

.SS "Message::Message (const \fBMessage\fP & aMessage)"

.PP
Constructeur par copie\&. 
.PP
\fBParameters\fP
.RS 4
\fIaMessage\fP message copié 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gestionnaire de parkings intelligents from the source code\&.
