.TH "Place" 3 "Tue Dec 13 2022" "Gestionnaire de parkings intelligents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Place
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlace\fP ()"
.br
.RI "constructeur de la place\&. "
.ti -1c
.RI "\fBPlace\fP (\fBVec2\fP pos, int indP)"
.br
.RI "constructeur à paramètre de \fBPlace\fP\&. "
.ti -1c
.RI "\fB~Place\fP ()"
.br
.RI "destructeur de la place\&. "
.ti -1c
.RI "const \fBVec2\fP & \fBgetPos\fP () const"
.br
.RI "position de la place\&. "
.ti -1c
.RI "const int & \fBgetIndP\fP () const"
.br
.RI "procédure de récupération de l'indice de la position de la place\&. "
.ti -1c
.RI "void \fBsetIsTaken\fP (bool new_isTaken)"
.br
.RI "met à jour la valeur de isTaken avec la valeur de "
.ti -1c
.RI "const bool & \fBgetIsTaken\fP () const"
.br
.RI "retourne le booléen isTaken\&. Vrai = place prise, faux sinon\&. "
.ti -1c
.RI "void \fBsetIsReserved\fP (bool new_isReserved)"
.br
.RI "met à jour la valeur de isReserved avec la valeur de "
.ti -1c
.RI "const bool & \fBgetIsReserved\fP () const"
.br
.RI "retourne le booléen isReserved\&. Vrai = place réservée, faux sinon\&. "
.ti -1c
.RI "void \fBtest_regresion\fP ()"
.br
.RI "test de régression de la classe \fBPlace\fP\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Place::setIsReserved (bool new_isReserved)"

.PP
met à jour la valeur de isReserved avec la valeur de 
.PP
\fBParameters\fP
.RS 4
\fInew_isReserved,un\fP booléen\&. 
.RE
.PP

.SS "void Place::setIsTaken (bool new_isTaken)"

.PP
met à jour la valeur de isTaken avec la valeur de 
.PP
\fBParameters\fP
.RS 4
\fInew_isTaken,un\fP booléen\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gestionnaire de parkings intelligents from the source code\&.
