.TH "Vec2" 3 "Tue Dec 13 2022" "Gestionnaire de parkings intelligents" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec2
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVec2\fP (float x, float y)"
.br
.RI "Constructeur de la classe \fBVec2\fP\&. "
.ti -1c
.RI "\fB~Vec2\fP ()"
.br
.RI "Destructeur de la classe \fBVec2\fP\&. "
.ti -1c
.RI "\fBVec2\fP \fBoperator+\fP (\fBVec2\fP New_vec)"
.br
.RI "Surcharge de l'opérateur +\&. "
.ti -1c
.RI "\fBVec2\fP \fBoperator*\fP (\fBVec2\fP New_vec)"
.br
.RI "Surcharge de l'opérateur *\&. "
.ti -1c
.RI "\fBVec2\fP \fBoperator*\fP (float New_float)"
.br
.RI "Surcharge de l'opérateur *\&. "
.ti -1c
.RI "const bool \fBoperator!=\fP (const \fBVec2\fP New_vec) const"
.br
.RI "Surcharge de l'opérateur !=\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "const bool Vec2::operator!= (const \fBVec2\fP New_vec) const"

.PP
Surcharge de l'opérateur !=\&. 
.PP
\fBParameters\fP
.RS 4
\fINew_vec\fP : vecteur à comparer 
.RE
.PP

.SS "\fBVec2\fP Vec2::operator* (float New_float)"

.PP
Surcharge de l'opérateur *\&. 
.PP
\fBParameters\fP
.RS 4
\fINew_float\fP : float à multiplier 
.RE
.PP

.SS "\fBVec2\fP Vec2::operator* (\fBVec2\fP New_vec)"

.PP
Surcharge de l'opérateur *\&. 
.PP
\fBParameters\fP
.RS 4
\fINew_vec\fP : vecteur à multiplier 
.RE
.PP

.SS "\fBVec2\fP Vec2::operator+ (\fBVec2\fP New_vec)"

.PP
Surcharge de l'opérateur +\&. 
.PP
\fBParameters\fP
.RS 4
\fINew_vec\fP : vecteur à ajouter 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gestionnaire de parkings intelligents from the source code\&.
